module.exports = {
    FB_PAGE_TOKEN: 'EAAfFkxJMuQMBAJG12gEKbb3kf9j0uTzZBi60o4ckMDooAU7djm5KCjfPwDAfusc7j6ZCUSBThXfiAQbHjSYTxNKb0tuNIBHCIzyUZAHzVMftJ7Tbn7sjSZB2tduhtJZCWtyqwZBg9VNtL6ViwVXTGZB7ZCAZA4aZColGHBJPLZBosNY7QZDZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};
